#!/bin/bash
[ -f ~/.bin/autostart.local ] && ~/.bin/autostart.local &

urxvtd=$(pidof urxvtd)
if [[ -z $urxvtd ]]; then
    /usr/bin/urxvtd -f -o -q
fi

/usr/bin/xscreensaver -no-splash &

BG=~/.bg/bg_triangular_glow.png
[ -f $BG ] && /usr/bin/feh --bg-scale $BG

/usr/bin/setxkbmap -option caps:none

/usr/bin/awesome
