set nocompatible              " be iMproved, required
filetype off                  " required

" ======== General settings ======== "
color peachpuff

" show line numbers
set number

" Don't jump over wrapped lines.
nnoremap j gj
nnoremap k gk

" turn on syntax highlighting
syntax on

" Highlight the current line.
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey40

" Enable a graphical menu for cycling through filenames.
set wildmenu

" Don't redreaw unless VIM really has to.
" This enables ex. faster macros.
set lazyredraw

" Show matching [({})]
set showmatch

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Handle packages
Plugin 'gmarik/Vundle.vim'

" Make vimdiff act sanely
Plugin 'tpope/vim-fugitive'
Plugin 'christoomey/vim-conflicted'

" Make the statusline more useful
Plugin 'bling/vim-airline'

" Allow HTML tag expansion
Plugin 'rstacruz/sparkup'

" Give each level of parentheses a distinct color
Plugin 'kien/rainbow_parentheses.vim'

" Make it easier to comment out large blocks
Plugin 'scrooloose/nerdcommenter'

" Give syntactic hints in realtime
Plugin 'scrooloose/syntastic'
Plugin 'fatih/vim-go'

" enable vim airline (bottom command bar)
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='raven'

let mapleader=","

autocmd StdinReadPre * let s:std_in=1

" use jj to got to command mode
imap jj <Esc>

" Handle long lines nicely.
set wrap
set textwidth=79
set formatoptions=qrn1

" make it possible to go to a other split by using ctrl+hjkl
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

nnoremap <C-S-tab> :tabprevious<CR>
nnoremap <C-tab>   :tabnext<CR>
nnoremap <C-t>     :tabnew<CR>
inoremap <C-S-tab> <Esc>:tabprevious<CR>i
inoremap <C-tab>   <Esc>:tabnext<CR>i
inoremap <C-t>     <Esc>:tabnew<CR>

call vundle#end()            " required by vundle
filetype plugin indent on    " required by vundle

set history=1000    " remember more commands and search history
set undolevels=1000 " use many muchos levels of undo

set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" auto enable rainbow ()
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

set visualbell           " don't beep
set noerrorbells         " don't beep

set title                " change the terminal's title

" Default Tabs & spaces
set tabstop=4     " a tab is four spaces
set shiftwidth=4  " number of spaces to use for autoindenting
set softtabstop=4
set copyindent    " copy the previous indentation on autoindenting
set expandtab
set smarttab
set autoindent

if v:version < 703
        finish
    endif
        autocmd InsertEnter * :set number
        autocmd InsertLeave * :set relativenumber

set pastetoggle=<F2>

set statusline=%<%F%h%m%r%=\[%B\]\ %l,%c%V\ %P

" " Always show the statusline
set laststatus=2

" Clear searches.
nnoremap <leader><space> :nohlsearch<CR>

" Higlight whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
