ZSH_ROOT=${HOME}/dotfiles/zsh

for ZSH_FILE in checks aliases bindkeys colors completion functions \
                history prompt exports setopt zsh_hooks; do

    filename=$ZSH_ROOT/includes/$ZSH_FILE.zsh
    if [[ -s $filename ]]; then
        eval source $filename
    fi
done

for ZSH_SCRIPT in z; do
    filename=$ZSH_ROOT/scripts/$ZSH_SCRIPT.sh
    if [[ -s $filename ]]; then
        eval source $filename
    fi
done

if [[ -s $ZSH_ROOT/zshrc.local ]]; then
    source $ZSH_ROOT/zshrc.local
fi

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi
