if [[ -s $HOME/dotfiles/zsh/zprezto/init.zsh ]]; then
	source $HOME/dotfiles/zsh/zprezto/init.zsh
fi
bindkey -M viins "jj" vi-cmd-mode


alias ll='ls -la'
alias tmuxkill="tmux kill-session -t"
alias tmuxattach="tmux attach-session -t"
alias tmuxls="tmux list-sessions"

bindkey "^J" history-search-backward
bindkey "^K" history-search-forward
alias trondheim='finger 7012@graph.no | grep -v NRK'

export LANG=en_US.UTF-8
source $HOME/.zshrc.local
